import SubsidiarySection from "./subsidiary_section";

const AllSubsidiaries = () =>{
    return (
        <div className="flex flex-col">
            <SubsidiarySection srcs={['resources/edu_img_1.png', 'resources/edu_img_2.png', 'resources/edu_img_3.png', 'resources/edu_img_2.png', 'resources/edu_img_2.png']} num_imgs={5} logo={'resources/education_section_logo.png'} text={"SPEEEX Education is an educational institution specializing in workforce training and development for the BPO/ICT sector. Its comprehensive training curricula include:"} btn_labels={['Language Modules', 'Technical Modules', 'Soft Skills & Communication', 'Customer Service', 'Sales']} num_btns={5} bg_color={"resources/s_bg_education.png"}/>
            <SubsidiarySection srcs={['resources/rhen_img_1.png', 'resources/rhen_img_2.png', 'resources/rhen_img_3.png', 'resources/rhen_img_2.png', 'resources/rhen_img_2.png']} num_imgs={5} logo={'resources/rhenum_section_logo.png'} text={"Rhenum is a specialized software development agency dedicated to crafting products and digital platforms that automate enterprise processes. Its core focus areas include:"} btn_labels={['App Development', 'IT Counseling', 'Information Security Audits', 'Web Development']} num_btns={4} bg_color={"resources/s_bg_rhenum.png"}/>
            <SubsidiarySection srcs={['resources/as_img_1.png', 'resources/as_img_2.png', 'resources/as_img_3.png', 'resources/as_img_4.png', 'resources/rhen_img_2.png']} num_imgs={4} logo={'resources/ascendio_section_logo.png'} text={"Asendio is a Learning Experience Platform (LXP), specializing in the delivery of AI-powered, gamified learning experiences that transform the way frontline teams acquire and apply knowledge. Our next-generation SaaS platform creates personalized, engaging, and interactive learning journeys designed to boost knowledge retention, enhance performance, and drive measurable business results."} btn_labels={['Leraning Management System Software', 'Customized Content Creation']} num_btns={2} bg_color={"resources/ascendio_bg_colorpng"}/>
            <SubsidiarySection srcs={['resources/md_img_1.png', 'resources/md_img_2.png', 'resources/md_img_3.png', 'resources/md_img_2.png', 'resources/md_img_2.png']} num_imgs={5} logo={'resources/medienhaus_section_logo.png'} text={"SPEEEX Medienhaus specializes in creating impactful digital advertising solutions tailored to meet the unique needs of our clients. With a focus on cutting-edge technology and creative strategies, we design compelling campaigns that maximize brand visibility and engagement across digital platforms. Our expertise includes targeted audience segmentation, data-driven campaign optimization, and comprehensive analytics to ensure measurable results and ROI for our partners."} btn_labels={['Digital Advertisement', 'Digital Marketing', 'SEO', 'Social Media Marketing', 'UI/UX Design']} num_btns={5} bg_color={"resources/md_bg_color.png"}/>
            <SubsidiarySection srcs={['resources/st_img_1.png', 'resources/st_img_2.png', 'resources/st_img_3.png', 'resources/st_img_4.png']} num_imgs={4} logo={'resources/staffify_section_logo.png'} text={"Staffify is a specialized recruitment process outsourcing company that excels in providing remote recruiters through staff leasing, and facilitating the formation of customized teams based in the Republic of Kosova."} btn_labels={['Recruitment Process Outsourcing', 'Remote Recruiters', 'Staff Leasing']} num_btns={3} bg_color={"resources/st_bg_color.png"}/>
        </div>
    );
}
export default AllSubsidiaries